defaults:
  - datamodule: calvin

ckpt_path: 
root_data_dir: 
train_folder:
lang_folder: lang_clip_resnet50

min_window_size: 21 
max_window_size: 50
future_range: 29
seed: 242
batch_size: 28
max_epochs: 12
log_every: 50
save_every: 2000
window_sampling_strategy: 'geometric'
num_workers: 12
img_gen_frame_diff: 3
val_num_batches: 20


act_seq_len: 50  # training action chunk
obs_seq_len: 1

model:
  _target_: policy_models.VPP_policy.VPP_Policy
  _recursive_: false
  latent_dim: 384
  multistep: 50
  sampler_type: 'ddim'
  num_sampling_steps: 10
  sigma_data: 0.5
  sigma_min: 0.001
  sigma_max: 80
  noise_scheduler: 'exponential'
  sigma_sample_density_type: 'loglogistic'
  use_lr_scheduler: true
  act_window_size: 50
  obs_seq_len: ${obs_seq_len}
  action_dim: 7
  action_seq_len: ${act_seq_len}
  first_steps_weight: 1.0
  first_steps_count: 0
  action_dim_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  use_text_not_embedding: True
  seed: ${seed}
  Former_depth: 6
  Former_heads: 8
  Former_dim_head: 64
  Former_num_time_embeds: 16
  num_latents: 224
  pretrained_model_path: 
  text_encoder_path: 
  t5_model_path: 
  language_goal_path: ckpt/ViT-B-32.pt
  use_position_encoding: False  # should be same with finetune settings
  use_Former: 3d
  timestep: 20
  use_all_layer: True
  extract_layer_idx: 1
  optimizer:
    _target_: torch.optim.AdamW
    transformer_weight_decay: 0.05
    learning_rate: 1e-4  # 如果用了scheduler，这个就没用了
    betas: [ 0.9, 0.9 ]
  lr_scheduler:
    lr_scheduler:
      init_lr: 1e-4  # 没用
      init_lr_scale: 0.1  # 初始学习率是 peak_lr * init_lr_scale
      final_lr_scale: 1e-6  # 最后的学习率是 peak_lr * final_lr_scale
      total_steps: 50000  # 调用lr scheduler的step次数
      phase_ratio: "(0.02, 0.08, 0.9)"  # 三个阶段的比例
      lr: 1e-4  # 这个是peak_lr
